Document: aubio-lv2
Title: Debian aubio-lv2 Manual
Author: <insert document author here>
Abstract: This manual describes what aubio-lv2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aubio-lv2/aubio-lv2.sgml.gz

Format: postscript
Files: /usr/share/doc/aubio-lv2/aubio-lv2.ps.gz

Format: text
Files: /usr/share/doc/aubio-lv2/aubio-lv2.text.gz

Format: HTML
Index: /usr/share/doc/aubio-lv2/html/index.html
Files: /usr/share/doc/aubio-lv2/html/*.html
